# Generated by Django 4.2.7 on 2023-12-01 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_search'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friend',
            name='friend',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='friend',
            name='user',
            field=models.CharField(max_length=100),
        ),
    ]
